In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

import gym
env = gym.make('CarRacing-v0')

import numpy as np
import itertools as it

import tensorflow as tf

from keras_agent import DQNAgent



# import torch
# import torch.nn.functional as F
# import torch.optim as optim

In [2]:
agent = DQNAgent(env)
sess = tf.InteractiveSession()
agent.session = sess
tf.global_variables_initializer().run()
saver = tf.train.Saver(max_to_keep=100)

---------- Initializing -----------
Action Map ->  [[-1.   1.   0.2]
 [-1.   1.   0. ]
 [-1.   0.   0.2]
 [-1.   0.   0. ]
 [ 0.   1.   0.2]
 [ 0.   1.   0. ]
 [ 0.   0.   0.2]
 [ 0.   0.   0. ]
 [ 1.   1.   0.2]
 [ 1.   1.   0. ]
 [ 1.   0.   0.2]
 [ 1.   0.   0. ]]


In [3]:
scores = []
frames_in_episodes = []
for i in range(10100):
    score, frames = agent.play_episode()
    scores.append(score)
    frames_in_episodes.append(frames)
    print('episode {}, score {}, frames {}, total_steps {}, network actions {}'.format(i, score, frames, agent.global_counter, agent.network_chosen_action))
#     if i % 250 == 0:
#         saver.save(sess, 'model.ckpt', agent.global_counter)

Track generation: 1104..1384 -> 280-tiles track
episode 0, score -9.278853046594955, frames 24, total_steps 24, network actions 0
Track generation: 1125..1410 -> 285-tiles track
episode 1, score 50.10704225352137, frames 48, total_steps 72, network actions 0
Track generation: 1102..1386 -> 284-tiles track
episode 2, score 15.136395759717217, frames 36, total_steps 108, network actions 0
Track generation: 1220..1529 -> 309-tiles track
episode 3, score -2.7259740259740752, frames 29, total_steps 137, network actions 0
Track generation: 972..1226 -> 254-tiles track
episode 4, score -1.0320158102767465, frames 29, total_steps 166, network actions 1
Track generation: 1163..1457 -> 294-tiles track
episode 5, score -7.922184300341266, frames 28, total_steps 194, network actions 1
Track generation: 1124..1409 -> 285-tiles track
episode 6, score 2.3901408450703556, frames 31, total_steps 225, network actions 1
Track generation: 1169..1465 -> 296-tiles track
episode 7, score 1.208474576271115, f

episode 59, score 4.661538461538338, frames 46, total_steps 1893, network actions 18
Track generation: 1149..1439 -> 290-tiles track
episode 60, score 17.04290657439438, frames 38, total_steps 1931, network actions 18
Track generation: 1101..1380 -> 279-tiles track
episode 61, score 6.07122302158265, frames 33, total_steps 1964, network actions 18
Track generation: 1048..1314 -> 266-tiles track
episode 62, score -5.758490566037745, frames 28, total_steps 1992, network actions 19
Track generation: 1210..1526 -> 316-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1200..1512 -> 312-tiles track
episode 63, score -3.876527331189756, frames 32, total_steps 2024, network actions 20
Track generation: 1148..1439 -> 291-tiles track
episode 64, score -10.258620689655142, frames 25, total_steps 2049, network actions 20
Track generation: 1080..1362 -> 282-tiles track
episode 65, score -3.488967971530304, frames 28, total_steps 2077, network acti

episode 112, score -10.617869415807531, frames 26, total_steps 3618, network actions 64
Track generation: 1150..1442 -> 292-tiles track
episode 113, score -4.645017182130619, frames 29, total_steps 3647, network actions 65
Track generation: 1164..1459 -> 295-tiles track
episode 114, score -4.590476190476233, frames 28, total_steps 3675, network actions 65
Track generation: 1164..1459 -> 295-tiles track
episode 115, score 0.11224489795910131, frames 35, total_steps 3710, network actions 70
Track generation: 1186..1487 -> 301-tiles track
episode 116, score -4.7666666666666995, frames 27, total_steps 3737, network actions 70
Track generation: 1188..1489 -> 301-tiles track
episode 117, score -2.3333333333333925, frames 30, total_steps 3767, network actions 70
Track generation: 1080..1363 -> 283-tiles track
episode 118, score -3.5773049645390635, frames 28, total_steps 3795, network actions 71
Track generation: 1076..1349 -> 273-tiles track
episode 119, score 44.305882352941396, frames 43, 

episode 167, score 7.0939849624059335, frames 35, total_steps 5443, network actions 140
Track generation: 1173..1471 -> 298-tiles track
episode 168, score -5.43097643097644, frames 30, total_steps 5473, network actions 141
Track generation: 1089..1367 -> 278-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1132..1419 -> 287-tiles track
episode 169, score 8.261538461538379, frames 34, total_steps 5507, network actions 142
Track generation: 1059..1336 -> 277-tiles track
episode 170, score 3.60869565217385, frames 30, total_steps 5537, network actions 142
Track generation: 1169..1465 -> 296-tiles track
episode 171, score -2.181355932203445, frames 31, total_steps 5568, network actions 142
Track generation: 1394..1748 -> 354-tiles track
episode 172, score -10.802832861189774, frames 26, total_steps 5594, network actions 142
Track generation: 1315..1648 -> 333-tiles track
episode 173, score -2.791566265060297, frames 33, total_steps 5627,

episode 223, score 1.3513409961685205, frames 31, total_steps 7223, network actions 233
Track generation: 1086..1362 -> 276-tiles track
episode 224, score -3.5454545454546, frames 30, total_steps 7253, network actions 234
Track generation: 964..1211 -> 247-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1152..1445 -> 293-tiles track
episode 225, score -8.452054794520514, frames 30, total_steps 7283, network actions 234
Track generation: 1116..1399 -> 283-tiles track
episode 226, score -7.1234042553191355, frames 28, total_steps 7311, network actions 238
Track generation: 1148..1439 -> 291-tiles track
episode 227, score 13.42758620689645, frames 38, total_steps 7349, network actions 241
Track generation: 1189..1497 -> 308-tiles track
episode 228, score -8.256026058631893, frames 26, total_steps 7375, network actions 242
Track generation: 1031..1299 -> 268-tiles track
episode 229, score -5.6280898876404635, frames 27, total_steps 7402

episode 282, score 23.691390728476705, frames 42, total_steps 9153, network actions 365
Track generation: 996..1249 -> 253-tiles track
episode 283, score 39.79682539682523, frames 52, total_steps 9205, network actions 373
Track generation: 1154..1447 -> 293-tiles track
episode 284, score -7.252054794520532, frames 26, total_steps 9231, network actions 373
Track generation: 1224..1534 -> 310-tiles track
episode 285, score -5.746278317152109, frames 28, total_steps 9259, network actions 376
Track generation: 1245..1560 -> 315-tiles track
episode 286, score -7.007006369426733, frames 31, total_steps 9290, network actions 378
Track generation: 1020..1279 -> 259-tiles track
episode 287, score -5.144186046511647, frames 28, total_steps 9318, network actions 381
Track generation: 1087..1363 -> 276-tiles track
episode 288, score 5.563636363636288, frames 36, total_steps 9354, network actions 382
Track generation: 1096..1377 -> 281-tiles track
episode 289, score -6.971428571428559, frames 28, t

episode 338, score -6.687421383647788, frames 29, total_steps 10975, network actions 529
Track generation: 1098..1384 -> 286-tiles track
episode 339, score 4.2877192982455306, frames 36, total_steps 11011, network actions 534
Track generation: 1209..1515 -> 306-tiles track
episode 340, score -8.127868852458986, frames 26, total_steps 11037, network actions 535
Track generation: 980..1230 -> 250-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1083..1358 -> 275-tiles track
episode 341, score 0.8467153284670772, frames 40, total_steps 11077, network actions 541
Track generation: 1244..1559 -> 315-tiles track
episode 342, score 1.3471337579617213, frames 35, total_steps 11112, network actions 544
Track generation: 1073..1351 -> 278-tiles track
episode 343, score 15.841516245487242, frames 49, total_steps 11161, network actions 548
Track generation: 1151..1443 -> 292-tiles track
episode 344, score 52.2470790378009, frames 57, total_steps

episode 395, score -11.324148606811107, frames 33, total_steps 13048, network actions 737
Track generation: 1018..1283 -> 265-tiles track
episode 396, score 5.0909090909090295, frames 30, total_steps 13078, network actions 741
Track generation: 1040..1304 -> 264-tiles track
episode 397, score 10.725095057034139, frames 37, total_steps 13115, network actions 745
Track generation: 1267..1588 -> 321-tiles track
episode 398, score 3.5749999999999282, frames 36, total_steps 13151, network actions 747
Track generation: 924..1159 -> 235-tiles track
episode 399, score 4.2880341880341035, frames 33, total_steps 13184, network actions 754
Track generation: 1105..1385 -> 280-tiles track
episode 400, score -6.594623655913976, frames 27, total_steps 13211, network actions 756
Track generation: 1260..1579 -> 319-tiles track
episode 401, score -9.53207547169808, frames 28, total_steps 13239, network actions 757
Track generation: 1084..1359 -> 275-tiles track
episode 402, score -7.402189781021875, fra

episode 452, score -10.806557377049153, frames 24, total_steps 14989, network actions 993
Track generation: 984..1234 -> 250-tiles track
episode 453, score -1.1875502008032655, frames 31, total_steps 15020, network actions 995
Track generation: 1127..1413 -> 286-tiles track
episode 454, score -0.9298245614035707, frames 30, total_steps 15050, network actions 998
Track generation: 1137..1426 -> 289-tiles track
episode 455, score 7.394444444444364, frames 36, total_steps 15086, network actions 1004
Track generation: 1072..1344 -> 272-tiles track
episode 456, score 24.940590405903933, frames 47, total_steps 15133, network actions 1009
Track generation: 1244..1559 -> 315-tiles track
episode 457, score -0.6375796178344508, frames 31, total_steps 15164, network actions 1017
Track generation: 1300..1629 -> 329-tiles track
episode 458, score -0.01219512195128658, frames 35, total_steps 15199, network actions 1021
Track generation: 1159..1453 -> 294-tiles track
episode 459, score -2.89624573378

episode 506, score 23.391390728476708, frames 43, total_steps 16929, network actions 1255
Track generation: 1100..1383 -> 283-tiles track
episode 507, score 14.399290780141747, frames 39, total_steps 16968, network actions 1261
Track generation: 1203..1508 -> 305-tiles track
episode 508, score 28.699999999999896, frames 46, total_steps 17014, network actions 1266
Track generation: 1204..1508 -> 304-tiles track
episode 509, score -3.79735973597365, frames 34, total_steps 17048, network actions 1275
Track generation: 1132..1419 -> 287-tiles track
episode 510, score -1.3279720279720877, frames 31, total_steps 17079, network actions 1279
Track generation: 1137..1425 -> 288-tiles track
episode 511, score -5.209756097560991, frames 32, total_steps 17111, network actions 1284
Track generation: 1187..1488 -> 301-tiles track
episode 512, score -11.7333333333333, frames 28, total_steps 17139, network actions 1288
Track generation: 1245..1560 -> 315-tiles track
episode 513, score 18.3554140127387

episode 562, score 6.46363636363629, frames 33, total_steps 18991, network actions 1618
Track generation: 1277..1601 -> 324-tiles track
episode 563, score -9.224148606811115, frames 26, total_steps 19017, network actions 1625
Track generation: 1159..1453 -> 294-tiles track
episode 564, score 18.594539249146663, frames 42, total_steps 19059, network actions 1634
Track generation: 1103..1383 -> 280-tiles track
episode 565, score -0.3261648745520347, frames 30, total_steps 19089, network actions 1639
Track generation: 1120..1404 -> 284-tiles track
episode 566, score -0.7314487632509454, frames 30, total_steps 19119, network actions 1642
Track generation: 1088..1364 -> 276-tiles track
episode 567, score -3.5454545454546, frames 30, total_steps 19149, network actions 1644
Track generation: 1196..1499 -> 303-tiles track
episode 568, score 2.3125827814568893, frames 36, total_steps 19185, network actions 1650
Track generation: 1152..1444 -> 292-tiles track
episode 569, score 38.36494845360813

episode 618, score 7.993984962405939, frames 32, total_steps 20963, network actions 1975
Track generation: 1198..1501 -> 303-tiles track
episode 619, score -5.221192052980154, frames 28, total_steps 20991, network actions 1980
Track generation: 1175..1473 -> 298-tiles track
episode 620, score -0.1969696969697523, frames 35, total_steps 21026, network actions 1993
Track generation: 1165..1460 -> 295-tiles track
episode 621, score -10.493197278911538, frames 25, total_steps 21051, network actions 1997
Track generation: 1101..1387 -> 286-tiles track
episode 622, score -4.438596491228115, frames 30, total_steps 21081, network actions 2002
Track generation: 1106..1394 -> 288-tiles track
episode 623, score 7.8275261324040954, frames 35, total_steps 21116, network actions 2012
Track generation: 1360..1704 -> 344-tiles track
episode 624, score -8.291836734693847, frames 29, total_steps 21145, network actions 2017
Track generation: 1143..1441 -> 298-tiles track
episode 625, score -5.13097643097

episode 674, score 45.060283687943425, frames 55, total_steps 22989, network actions 2400
Track generation: 1031..1293 -> 262-tiles track
episode 675, score -8.042911877394612, frames 24, total_steps 23013, network actions 2402
Track generation: 1163..1458 -> 295-tiles track
episode 676, score -1.7891156462585656, frames 30, total_steps 23043, network actions 2404
Track generation: 1053..1327 -> 274-tiles track
episode 677, score -2.095970695970756, frames 38, total_steps 23081, network actions 2412
Track generation: 1176..1478 -> 302-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1299..1628 -> 329-tiles track
episode 678, score 2.7365853658535855, frames 36, total_steps 23117, network actions 2417
Track generation: 1216..1525 -> 309-tiles track
episode 679, score 10.207792207792131, frames 40, total_steps 23157, network actions 2425
Track generation: 1215..1523 -> 308-tiles track
episode 680, score 24.831921824104107, frames 46, t

episode 731, score 2.52727272727266, frames 34, total_steps 25029, network actions 2827
Track generation: 1110..1399 -> 289-tiles track
episode 732, score -7.866666666666639, frames 29, total_steps 25058, network actions 2831
Track generation: 1108..1389 -> 281-tiles track
episode 733, score -4.000000000000053, frames 30, total_steps 25088, network actions 2834
Track generation: 1179..1478 -> 299-tiles track
episode 734, score -3.0543624161074376, frames 33, total_steps 25121, network actions 2842
Track generation: 1187..1488 -> 301-tiles track
episode 735, score -3.5333333333333883, frames 34, total_steps 25155, network actions 2853
Track generation: 1164..1459 -> 295-tiles track
episode 736, score 42.93129251700689, frames 51, total_steps 25206, network actions 2861
Track generation: 1275..1599 -> 324-tiles track
episode 737, score -5.432198142414872, frames 34, total_steps 25240, network actions 2872
Track generation: 1165..1460 -> 295-tiles track
episode 738, score -6.6904761904761

episode 790, score 29.924528301886617, frames 60, total_steps 27092, network actions 3345
Track generation: 1187..1488 -> 301-tiles track
episode 791, score -7.799999999999974, frames 26, total_steps 27118, network actions 3350
Track generation: 1123..1408 -> 285-tiles track
episode 792, score 61.712676056338495, frames 68, total_steps 27186, network actions 3364
Track generation: 1036..1299 -> 263-tiles track
episode 793, score -6.099236641221374, frames 30, total_steps 27216, network actions 3374
Track generation: 1203..1508 -> 305-tiles track
episode 794, score 28.699999999999896, frames 46, total_steps 27262, network actions 3388
Track generation: 1143..1431 -> 288-tiles track
episode 795, score -7.494076655052247, frames 28, total_steps 27290, network actions 3398
Track generation: 1235..1557 -> 322-tiles track
episode 796, score -9.70841121495324, frames 28, total_steps 27318, network actions 3401
Track generation: 1019..1284 -> 265-tiles track
episode 797, score 11.4666666666665

episode 846, score -6.273684210526316, frames 31, total_steps 29079, network actions 3838
Track generation: 1097..1375 -> 278-tiles track
episode 847, score 35.09205776173275, frames 45, total_steps 29124, network actions 3851
Track generation: 1288..1614 -> 326-tiles track
episode 848, score 9.353846153846021, frames 56, total_steps 29180, network actions 3862
Track generation: 1304..1634 -> 330-tiles track
episode 849, score -4.383890577507641, frames 29, total_steps 29209, network actions 3869
Track generation: 1099..1386 -> 287-tiles track
episode 850, score -4.824475524475552, frames 31, total_steps 29240, network actions 3881
Track generation: 1155..1456 -> 301-tiles track
episode 851, score -9.899999999999961, frames 33, total_steps 29273, network actions 3897
Track generation: 1076..1349 -> 273-tiles track
episode 852, score -6.341176470588232, frames 28, total_steps 29301, network actions 3904
Track generation: 1304..1634 -> 330-tiles track
episode 853, score -12.0024316109422

episode 903, score 0.004029304029245395, frames 31, total_steps 30958, network actions 4364
Track generation: 1101..1386 -> 285-tiles track
episode 904, score -1.5098591549296216, frames 44, total_steps 31002, network actions 4376
Track generation: 1100..1379 -> 279-tiles track
episode 905, score 18.35683453237398, frames 52, total_steps 31054, network actions 4390
Track generation: 1172..1469 -> 297-tiles track
episode 906, score -1.9729729729730323, frames 30, total_steps 31084, network actions 4397
Track generation: 1052..1319 -> 267-tiles track
episode 907, score -1.3248120300752433, frames 38, total_steps 31122, network actions 4411
Track generation: 1047..1313 -> 266-tiles track
episode 908, score -8.632075471698085, frames 25, total_steps 31147, network actions 4418
Track generation: 1097..1381 -> 284-tiles track
episode 909, score -6.898586572438155, frames 27, total_steps 31174, network actions 4426
Track generation: 1191..1493 -> 302-tiles track
episode 910, score -8.76644518

episode 958, score -5.6273972602739875, frames 32, total_steps 32838, network actions 4904
Track generation: 1059..1328 -> 269-tiles track
episode 959, score 6.513432835820808, frames 36, total_steps 32874, network actions 4913
Track generation: 1103..1383 -> 280-tiles track
episode 960, score -9.278853046594955, frames 24, total_steps 32898, network actions 4918
Track generation: 1188..1496 -> 308-tiles track
episode 961, score -10.956026058631883, frames 35, total_steps 32933, network actions 4930
Track generation: 1134..1422 -> 288-tiles track
episode 962, score -10.378397212543526, frames 26, total_steps 32959, network actions 4936
Track generation: 998..1252 -> 254-tiles track
episode 963, score 5.073122529644195, frames 35, total_steps 32994, network actions 4948
Track generation: 1305..1635 -> 330-tiles track
episode 964, score 9.353191489361613, frames 44, total_steps 33038, network actions 4959
Track generation: 1122..1416 -> 294-tiles track
episode 965, score -8.8221843003412

In [ ]:
from keras.models import load_model

agent.model.load_weights('model.h5')

In [ ]:
a = np.array([[1, 2], [3, 4]])
mask = np.zeros(a.shape, dtype=bool)
b = np.array([0,1])
# mask[b] = True
# np.ma.masked_array(a, b)


In [ ]:
for _ in range(20):
    env.render()
    obs, r, d, _ = env.step(env.action_space.sample())
    
plt.imshow(obs)

In [ ]:
obs = env.reset()

In [ ]:
env.close()

In [ ]:
plt.imshow(obs)

In [ ]:
ob2 = np.swapaxes(obs, 0, 2)

In [ ]:
ob2.shape

In [ ]:
obs.shape

In [ ]:
o = np.reshape(obs, (3,96,96))

In [ ]:
o == ob2

In [ ]:
from torchvision import transforms    

o = transforms.ToPILImage()(obs)

In [ ]:
o

In [ ]:
torch.device('cpu')

In [ ]:
from skimage import color

def process_image(img):
    return 2 * color.rgb2gray(img) - 1

In [ ]:
# agent.training_model.load_state_dict(torch.load('checkpoint.pth', map_location='cpu'))

for i in range(10):
#     states = deque(maxlen = 3)
    state = env.reset()
    for j in range(500):  
        state = process_image(state)
        action_idx = agent.get_action_for_state([state, state, state])
        print(action_idx)
        env.render()
        state, reward, done, _ = env.step(agent.action_map[action_idx])
        if done:
            break 
            
env.close()

In [ ]:
state = env.reset()
state = process_image(state)
for _ in range(1000):
    print('-------------------------------------')
    env.render()
    action_idx = get_random_action()
    action = all_actions[action_idx]
    print('Action -> ', action)
    next_state, reward, done, info = env.step(env.action_space.sample())
    print('Reward ->', reward)
    print('Done ->', done)
    next_state = process_image(next_state)
    print(next_state.shape)
    memory.add(state, action_idx, reward, next_state, done)
    state = next_state    
    print('-------------------------------------')


In [ ]:
4e-4

In [ ]:
env.close()

In [ ]:
a = [1,2,3,4,5,6]
a[-2:]

In [ ]:
a = np.ones(12)
a[1] = 9
a[2] = 9
a[3] = 9
b = np.ones(3, dtype='int32')
b[0] = 1
b[1] = 2
b[2] = 3

a[b]