In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

import gym
env = gym.make('CarRacing-v0')

import numpy as np
import itertools as it

from keras_agent import DQNAgent

Using TensorFlow backend.


In [2]:
agent = DQNAgent(env)

---------- Initializing -----------
Action Map ->  [[-1.   1.   0.2]
 [-1.   1.   0. ]
 [-1.   0.   0.2]
 [-1.   0.   0. ]
 [ 0.   1.   0.2]
 [ 0.   1.   0. ]
 [ 0.   0.   0.2]
 [ 0.   0.   0. ]
 [ 1.   1.   0.2]
 [ 1.   1.   0. ]
 [ 1.   0.   0.2]
 [ 1.   0.   0. ]]


/Users/harsh/code/nn/project/f-dqn/keras_agent.py:93: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
  model.add(MaxPooling2D(pool_size = (2, 2), dim_ordering="th"))
/Users/harsh/code/nn/project/f-dqn/keras_agent.py:96: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
  model.add(MaxPooling2D(pool_size = (2, 2), dim_ordering="th"))


---------- Model ---------
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 8, 90, 90)         1184      
_________________________________________________________________
batch_normalization_1 (Batch (None, 8, 90, 90)         360       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 45, 45)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 6, 43, 16)         6496      
_________________________________________________________________
batch_normalization_2 (Batch (None, 6, 43, 16)         64        
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 6, 21, 8)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1008)        

In [3]:
scores = []
frames_in_episodes = []
for i in range(5000):
    score, frames = agent.play_episode()
    scores.append(score)
    frames_in_episodes.append(frames)
    print(i, score, frames)
    if i % 300 == 0:
        model_json = agent.model.to_json()
        with open("model.json", "w") as json_file:
            json_file.write(model_json)
        # serialize weights to HDF5
        agent.model.save_weights("model-{}.h5".format(agent.global_counter))
        print("Saved model to disk")

Track generation: 1155..1448 -> 293-tiles track
0 -1.3027397260274611 29
Saved model to disk
Track generation: 1335..1673 -> 338-tiles track
1 -9.995845697329347 26
Track generation: 1169..1465 -> 296-tiles track
2 0.9084745762711108 32
Track generation: 1115..1398 -> 283-tiles track
3 5.860992907801339 32
Track generation: 1279..1603 -> 324-tiles track
4 -9.524148606811114 27
Track generation: 1265..1593 -> 328-tiles track
5 8.055351681957106 39
Track generation: 1131..1418 -> 287-tiles track
6 1.8685314685313976 32
Track generation: 1359..1703 -> 344-tiles track
7 4.185422740524704 36
Track generation: 1127..1413 -> 286-tiles track
8 4.8877192982455355 34
Track generation: 1103..1383 -> 280-tiles track
9 3.2580645161289645 30
Track generation: 1177..1475 -> 298-tiles track
10 15.138047138047064 40
Track generation: 1140..1437 -> 297-tiles track
11 9.740540540540458 36
Track generation: 1220..1529 -> 309-tiles track
12 5.214285714285648 35
Track generation: 1231..1543 -> 312-tiles tra

104 -2.333333333333396 30
Track generation: 1119..1409 -> 290-tiles track
105 -4.7785467128027985 30
Track generation: 1019..1278 -> 259-tiles track
106 12.135658914728602 35
Track generation: 1099..1378 -> 279-tiles track
107 6.071223021582647 33
Track generation: 1132..1418 -> 286-tiles track
108 -0.62982456140357 29
Track generation: 1234..1547 -> 313-tiles track
109 -4.858974358974393 35
Track generation: 1069..1350 -> 281-tiles track
110 12.357142857142776 35
Track generation: 1175..1473 -> 298-tiles track
111 9.904040404040323 35
Track generation: 987..1238 -> 251-tiles track
112 20.599999999999895 38
Track generation: 1097..1375 -> 278-tiles track
113 -9.449458483754485 25
Track generation: 987..1245 -> 258-tiles track
114 -1.4626459143969406 29
Track generation: 1167..1463 -> 296-tiles track
115 6.188135593220245 37
Track generation: 1075..1348 -> 273-tiles track
116 -8.817647058823503 24
Track generation: 1064..1334 -> 270-tiles track
117 17.527137546468317 36
Track generation

206 -8.703007518796964 25
Track generation: 1110..1400 -> 290-tiles track
207 -9.898961937716235 24
Track generation: 1120..1404 -> 284-tiles track
208 -9.532155477031775 24
Track generation: 1067..1341 -> 274-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1018..1278 -> 260-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1090..1375 -> 285-tiles track
209 -0.8309859154930201 30
Track generation: 1176..1474 -> 298-tiles track
210 -9.397979797979762 32
Track generation: 1172..1469 -> 297-tiles track
211 7.340540540540438 44
Track generation: 1187..1487 -> 300-tiles track
212 0.5003344481604657 32
Track generation: 1156..1449 -> 293-tiles track
213 25.019178082191665 44
Track generation: 1180..1479 -> 299-tiles track
214 -5.810067114093968 31
Track generation: 1232..1544 -> 312-tiles track
215 -0.36109324758847805 31
Track generation: 974..1225 -> 251-tiles track
216 2.6999999999999

301 -3.1441471571906945 33
Track generation: 1105..1385 -> 280-tiles track
302 13.079211469533888 57
Track generation: 1060..1329 -> 269-tiles track
303 -3.4805970149254257 32
Track generation: 1190..1492 -> 302-tiles track
304 15.111627906976658 38
Track generation: 1103..1388 -> 285-tiles track
305 1.9323943661970162 56
Track generation: 1064..1340 -> 276-tiles track
306 3.127272727272654 32
Track generation: 1192..1494 -> 302-tiles track
307 0.00033222591356718567 33
Track generation: 1028..1289 -> 261-tiles track
308 8.86153846153838 32
Track generation: 1131..1418 -> 287-tiles track
309 -7.420979020978997 28
Track generation: 1003..1264 -> 261-tiles track
310 0.8692307692307075 33
Track generation: 924..1164 -> 240-tiles track
311 -6.8794979079497836 26
Track generation: 1063..1333 -> 270-tiles track
312 0.7397769516728019 30
Track generation: 1203..1508 -> 305-tiles track
313 -8.963157894736812 29
Track generation: 1161..1455 -> 294-tiles track
314 13.268600682593771 37
Track gen

KeyboardInterrupt: 

In [ ]:
from keras.models import load_model

agent.model.load_weights('model.h5')

In [ ]:
a = np.array([[1, 2], [3, 4]])
mask = np.zeros(a.shape, dtype=bool)
b = np.array([0,1])
# mask[b] = True
# np.ma.masked_array(a, b)


In [ ]:
for _ in range(20):
    env.render()
    obs, r, d, _ = env.step(env.action_space.sample())
    
plt.imshow(obs)

In [ ]:
obs = env.reset()

In [ ]:
env.close()

In [ ]:
plt.imshow(obs)

In [ ]:
ob2 = np.swapaxes(obs, 0, 2)

In [ ]:
ob2.shape

In [ ]:
obs.shape

In [ ]:
o = np.reshape(obs, (3,96,96))

In [ ]:
o == ob2

In [ ]:
from torchvision import transforms    

o = transforms.ToPILImage()(obs)

In [ ]:
o

In [ ]:
torch.device('cpu')

In [ ]:
from skimage import color

def process_image(img):
    return 2 * color.rgb2gray(img) - 1

In [ ]:
# agent.training_model.load_state_dict(torch.load('checkpoint.pth', map_location='cpu'))

for i in range(10):
#     states = deque(maxlen = 3)
    state = env.reset()
    for j in range(500):  
        state = process_image(state)
        action_idx = agent.get_action_for_state([state, state, state])
        print(action_idx)
        env.render()
        state, reward, done, _ = env.step(agent.action_map[action_idx])
        if done:
            break 
            
env.close()

In [ ]:
state = env.reset()
state = process_image(state)
for _ in range(1000):
    print('-------------------------------------')
    env.render()
    action_idx = get_random_action()
    action = all_actions[action_idx]
    print('Action -> ', action)
    next_state, reward, done, info = env.step(env.action_space.sample())
    print('Reward ->', reward)
    print('Done ->', done)
    next_state = process_image(next_state)
    print(next_state.shape)
    memory.add(state, action_idx, reward, next_state, done)
    state = next_state    
    print('-------------------------------------')


In [ ]:
4e-4

In [ ]:
env.close()

In [ ]:
a = [1,2,3,4,5,6]
a[-2:]

In [ ]:
a = np.ones(12)
a[1] = 9
a[2] = 9
a[3] = 9
b = np.ones(3, dtype='int32')
b[0] = 1
b[1] = 2
b[2] = 3

a[b]