In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

import gym
env = gym.make('CarRacing-v0')

import numpy as np
import itertools as it

import tensorflow as tf

from keras_agent import DQNAgent



# import torch
# import torch.nn.functional as F
# import torch.optim as optim

In [8]:
from collections import deque

a = deque(maxlen = 2)
a.append(1)
print(a)
a.append(2)

deque([1], maxlen=2)


In [9]:
a

deque([1, 2])

In [11]:
a.append(3)
a

deque([3, 3])

In [2]:
agent = DQNAgent(env)
sess = tf.InteractiveSession()
agent.session = sess
tf.global_variables_initializer().run()
saver = tf.train.Saver(max_to_keep=100)

---------- Initializing -----------
Action Map ->  [[-1.   1.   0.2]
 [-1.   1.   0. ]
 [-1.   0.   0.2]
 [-1.   0.   0. ]
 [ 0.   1.   0.2]
 [ 0.   1.   0. ]
 [ 0.   0.   0.2]
 [ 0.   0.   0. ]
 [ 1.   1.   0.2]
 [ 1.   1.   0. ]
 [ 1.   0.   0.2]
 [ 1.   0.   0. ]]


In [3]:
scores = []
frames_in_episodes = []
for i in range(1000):
    score, frames = agent.play_episode()
    scores.append(score)
    frames_in_episodes.append(frames)
    print('episode {}, score {}, frames {}, total_steps {}, network actions {}'.format(i, score, frames, agent.global_counter, agent.network_chosen_action))
#     if i % 250 == 0:
#         saver.save(sess, 'model.ckpt', agent.global_counter)

Track generation: 1043..1308 -> 265-tiles track
episode 0, score 4.790909090909029, frames 31, total_steps 31, network actions 0
Track generation: 1101..1380 -> 279-tiles track
episode 1, score -3.5201438848921462, frames 29, total_steps 60, network actions 0
Track generation: 1264..1584 -> 320-tiles track
episode 2, score -4.221630094043938, frames 31, total_steps 91, network actions 0
Track generation: 1137..1425 -> 288-tiles track
episode 3, score -9.778397212543528, frames 24, total_steps 115, network actions 0
Track generation: 1175..1473 -> 298-tiles track
episode 4, score -7.597979797979777, frames 26, total_steps 141, network actions 0
Track generation: 1221..1530 -> 309-tiles track
episode 5, score 8.6545454545453, frames 56, total_steps 197, network actions 0
Track generation: 1268..1589 -> 321-tiles track
episode 6, score 1.6499999999999346, frames 32, total_steps 229, network actions 0
Track generation: 1068..1341 -> 273-tiles track
retry to generate track (normal if there 

episode 55, score 13.456043956043878, frames 35, total_steps 1852, network actions 20
Track generation: 1247..1563 -> 316-tiles track
episode 56, score -6.77777777777777, frames 30, total_steps 1882, network actions 22
Track generation: 1059..1329 -> 270-tiles track
episode 57, score 58.236802973977944, frames 49, total_steps 1931, network actions 22
Track generation: 1108..1389 -> 281-tiles track
episode 58, score -6.971428571428559, frames 28, total_steps 1959, network actions 22
Track generation: 1012..1269 -> 257-tiles track
episode 59, score -0.7562500000000654, frames 27, total_steps 1986, network actions 22
Track generation: 1144..1434 -> 290-tiles track
episode 60, score -7.338754325259499, frames 27, total_steps 2013, network actions 22
Track generation: 988..1248 -> 260-tiles track
episode 61, score 12.57104247104239, frames 33, total_steps 2046, network actions 22
Track generation: 1152..1451 -> 299-tiles track
episode 62, score -4.910067114093993, frames 28, total_steps 207

episode 114, score 21.57205387205378, frames 41, total_steps 3876, network actions 71
Track generation: 1231..1541 -> 310-tiles track
episode 115, score -9.282524271844627, frames 29, total_steps 3905, network actions 72
Track generation: 1147..1438 -> 291-tiles track
episode 116, score 53.75517241379336, frames 53, total_steps 3958, network actions 74
Track generation: 1068..1339 -> 271-tiles track
episode 117, score 3.733333333333256, frames 32, total_steps 3990, network actions 75
Track generation: 1134..1422 -> 288-tiles track
episode 118, score -4.609756097561018, frames 30, total_steps 4020, network actions 76
Track generation: 1313..1645 -> 332-tiles track
episode 119, score 13.617220543806553, frames 39, total_steps 4059, network actions 77
Track generation: 1042..1305 -> 263-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1130..1416 -> 286-tiles track
episode 120, score -0.9298245614035743, frames 30, total_steps 4089, netw

episode 171, score 41.89881422924901, frames 44, total_steps 5760, network actions 162
Track generation: 1031..1293 -> 262-tiles track
episode 172, score 4.582758620689582, frames 33, total_steps 5793, network actions 162
Track generation: 1059..1328 -> 269-tiles track
episode 173, score 3.982089552238733, frames 32, total_steps 5825, network actions 165
Track generation: 1013..1278 -> 265-tiles track
episode 174, score -5.372727272727291, frames 27, total_steps 5852, network actions 166
Track generation: 1136..1424 -> 288-tiles track
episode 175, score -7.794076655052239, frames 29, total_steps 5881, network actions 168
Track generation: 1069..1345 -> 276-tiles track
episode 176, score -1.1090909090909662, frames 34, total_steps 5915, network actions 171
Track generation: 1304..1634 -> 330-tiles track
episode 177, score -7.123404255319132, frames 28, total_steps 5943, network actions 174
Track generation: 1076..1352 -> 276-tiles track
retry to generate track (normal if there are not m

episode 228, score 43.806148867314064, frames 57, total_steps 7559, network actions 275
Track generation: 1228..1539 -> 311-tiles track
episode 229, score -2.893548387096825, frames 29, total_steps 7588, network actions 277
Track generation: 1203..1508 -> 305-tiles track
episode 230, score -8.663157894736813, frames 28, total_steps 7616, network actions 281
Track generation: 1156..1449 -> 293-tiles track
episode 231, score -1.6027397260274618, frames 30, total_steps 7646, network actions 283
Track generation: 1267..1588 -> 321-tiles track
episode 232, score -6.225000000000001, frames 27, total_steps 7673, network actions 284
Track generation: 1076..1357 -> 281-tiles track
episode 233, score -1.0285714285714853, frames 32, total_steps 7705, network actions 287
Track generation: 1042..1310 -> 268-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1136..1433 -> 297-tiles track
retry to generate track (normal if there are not many of this 

episode 285, score -0.5947368421053234, frames 34, total_steps 9361, network actions 417
Track generation: 1135..1423 -> 288-tiles track
episode 286, score -6.894076655052256, frames 26, total_steps 9387, network actions 417
Track generation: 1099..1386 -> 287-tiles track
episode 287, score -4.224475524475572, frames 29, total_steps 9416, network actions 418
Track generation: 1199..1503 -> 304-tiles track
episode 288, score -8.598019801980167, frames 28, total_steps 9444, network actions 423
Track generation: 1221..1530 -> 309-tiles track
episode 289, score -5.972727272727278, frames 29, total_steps 9473, network actions 425
Track generation: 1061..1330 -> 269-tiles track
episode 290, score -3.1805970149254286, frames 31, total_steps 9504, network actions 429
Track generation: 1339..1678 -> 339-tiles track
episode 291, score -0.31420118343202574, frames 33, total_steps 9537, network actions 430
Track generation: 1347..1688 -> 341-tiles track
episode 292, score -6.070588235294114, frame

episode 339, score 16.472727272727177, frames 36, total_steps 11089, network actions 595
Track generation: 1140..1429 -> 289-tiles track
episode 340, score 1.3499999999999233, frames 33, total_steps 11122, network actions 599
Track generation: 1176..1474 -> 298-tiles track
episode 341, score -8.197979797979764, frames 28, total_steps 11150, network actions 602
Track generation: 1183..1483 -> 300-tiles track
episode 342, score 2.3448160535116394, frames 37, total_steps 11187, network actions 605
Track generation: 1061..1333 -> 272-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1232..1544 -> 312-tiles track
episode 343, score -3.576527331189766, frames 31, total_steps 11218, network actions 607
Track generation: 1155..1464 -> 309-tiles track
episode 344, score -8.31948051948049, frames 26, total_steps 11244, network actions 610
Track generation: 1201..1505 -> 304-tiles track
episode 345, score 1.3033003300329256, frames 39, total_ste

episode 394, score -5.435168195718674, frames 33, total_steps 13018, network actions 822
Track generation: 1019..1278 -> 259-tiles track
episode 395, score -4.244186046511675, frames 25, total_steps 13043, network actions 828
Track generation: 1268..1589 -> 321-tiles track
episode 396, score 21.849999999999888, frames 48, total_steps 13091, network actions 836
Track generation: 1087..1369 -> 282-tiles track
episode 397, score -6.447686832740214, frames 26, total_steps 13117, network actions 838
Track generation: 1093..1370 -> 277-tiles track
episode 398, score -7.560869565217365, frames 31, total_steps 13148, network actions 841
Track generation: 1128..1424 -> 296-tiles track
episode 399, score -6.861016949152539, frames 24, total_steps 13172, network actions 843
Track generation: 1200..1504 -> 304-tiles track
episode 400, score 8.203960396039527, frames 38, total_steps 13210, network actions 846
Track generation: 1171..1465 -> 294-tiles track
episode 401, score 4.229692832764421, fram

episode 452, score 10.279310344827486, frames 37, total_steps 14984, network actions 1053
Track generation: 1183..1483 -> 300-tiles track
episode 453, score -2.5441471571906824, frames 31, total_steps 15015, network actions 1058
Track generation: 1056..1324 -> 268-tiles track
episode 454, score 3.20786516853925, frames 35, total_steps 15050, network actions 1063
Track generation: 992..1244 -> 252-tiles track
episode 455, score -0.811553784860628, frames 29, total_steps 15079, network actions 1068
Track generation: 1218..1526 -> 308-tiles track
episode 456, score -8.85602605863189, frames 28, total_steps 15107, network actions 1073
Track generation: 1016..1274 -> 258-tiles track
episode 457, score 8.710505836575784, frames 34, total_steps 15141, network actions 1077
Track generation: 1168..1464 -> 296-tiles track
episode 458, score -7.761016949152522, frames 27, total_steps 15168, network actions 1083
Track generation: 1155..1448 -> 293-tiles track
episode 459, score -4.727397260274012,

episode 508, score 12.357142857142776, frames 35, total_steps 16836, network actions 1308
Track generation: 1080..1354 -> 274-tiles track
episode 509, score 6.130036630036557, frames 35, total_steps 16871, network actions 1314
Track generation: 1186..1487 -> 301-tiles track
episode 510, score 9.499999999999908, frames 35, total_steps 16906, network actions 1317
Track generation: 1108..1396 -> 288-tiles track
episode 511, score 25.433449477351765, frames 46, total_steps 16952, network actions 1325
Track generation: 1104..1384 -> 280-tiles track
episode 512, score 2.9580645161289603, frames 31, total_steps 16983, network actions 1332
Track generation: 1005..1264 -> 259-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1224..1534 -> 310-tiles track
episode 513, score -8.68252427184463, frames 27, total_steps 17010, network actions 1332
Track generation: 1041..1305 -> 264-tiles track
episode 514, score -8.488593155893508, frames 25, total

episode 565, score 27.892063492063322, frames 52, total_steps 18778, network actions 1620
Track generation: 1253..1570 -> 317-tiles track
episode 566, score 22.562025316455568, frames 48, total_steps 18826, network actions 1630
Track generation: 1208..1514 -> 306-tiles track
episode 567, score 30.273770491803177, frames 51, total_steps 18877, network actions 1634
Track generation: 1120..1404 -> 284-tiles track
episode 568, score -4.5650176678445735, frames 31, total_steps 18908, network actions 1636
Track generation: 1352..1694 -> 342-tiles track
episode 569, score -0.641935483871027, frames 43, total_steps 18951, network actions 1645
Track generation: 1220..1529 -> 309-tiles track
episode 570, score 33.48181818181804, frames 49, total_steps 19000, network actions 1654
Track generation: 1070..1344 -> 274-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1095..1378 -> 283-tiles track
episode 571, score -3.277304964539063, frames 27, to

episode 621, score -10.30810810810808, frames 24, total_steps 20758, network actions 1952
Track generation: 1123..1408 -> 285-tiles track
episode 622, score -1.1309859154930209, frames 31, total_steps 20789, network actions 1957
Track generation: 1160..1454 -> 294-tiles track
episode 623, score 1.8296928327644046, frames 41, total_steps 20830, network actions 1961
Track generation: 1233..1545 -> 312-tiles track
episode 624, score 4.8697749196140805, frames 35, total_steps 20865, network actions 1968
Track generation: 1115..1398 -> 283-tiles track
episode 625, score -3.577304964539067, frames 28, total_steps 20893, network actions 1972
Track generation: 1056..1321 -> 265-tiles track
episode 626, score -5.072727272727295, frames 26, total_steps 20919, network actions 1979
Track generation: 1073..1346 -> 273-tiles track
episode 627, score -1.6882352941176997, frames 37, total_steps 20956, network actions 1983
Track generation: 1047..1320 -> 273-tiles track
episode 628, score 16.0941176470

episode 679, score -9.342857142857115, frames 24, total_steps 22786, network actions 2350
Track generation: 1197..1504 -> 307-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1171..1468 -> 297-tiles track
episode 680, score 9.44054054054046, frames 37, total_steps 22823, network actions 2358
Track generation: 1131..1418 -> 287-tiles track
episode 681, score -8.620979020978984, frames 32, total_steps 22855, network actions 2366
Track generation: 984..1242 -> 258-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1152..1444 -> 292-tiles track
episode 682, score 0.4278350515463174, frames 35, total_steps 22890, network actions 2370
Track generation: 1092..1369 -> 277-tiles track
episode 683, score -6.060869565217395, frames 26, total_steps 22916, network actions 2376
Track generation: 977..1225 -> 248-tiles track
episode 684, score 8.485829959514056, frames 40, total_steps 22956, networ

episode 736, score 7.562283737024149, frames 35, total_steps 24872, network actions 2799
Track generation: 1286..1612 -> 326-tiles track
episode 737, score 3.3461538461537756, frames 35, total_steps 24907, network actions 2808
Track generation: 1105..1390 -> 285-tiles track
episode 738, score -3.7521126760563916, frames 28, total_steps 24935, network actions 2817
Track generation: 1164..1459 -> 295-tiles track
episode 739, score 40.63265306122433, frames 70, total_steps 25005, network actions 2837
Track generation: 1272..1594 -> 322-tiles track
episode 740, score 3.5831775700933832, frames 46, total_steps 25051, network actions 2852
Track generation: 1051..1328 -> 277-tiles track
episode 741, score -6.960869565217381, frames 29, total_steps 25080, network actions 2858
Track generation: 1212..1519 -> 307-tiles track
episode 742, score 5.447712418300576, frames 35, total_steps 25115, network actions 2863
Track generation: 1164..1459 -> 295-tiles track
episode 743, score -10.7931972789115

episode 792, score -12.184984984984958, frames 24, total_steps 26963, network actions 3303
Track generation: 1108..1396 -> 288-tiles track
episode 793, score -4.009756097561031, frames 28, total_steps 26991, network actions 3310
Track generation: 1068..1339 -> 271-tiles track
episode 794, score 9.640740740740654, frames 37, total_steps 27028, network actions 3320
Track generation: 883..1115 -> 232-tiles track
episode 795, score 21.44805194805184, frames 35, total_steps 27063, network actions 3328
Track generation: 972..1219 -> 247-tiles track
episode 796, score 10.750406504064962, frames 33, total_steps 27096, network actions 3337
Track generation: 1217..1526 -> 309-tiles track
episode 797, score -4.225974025974072, frames 34, total_steps 27130, network actions 3346
Track generation: 1044..1309 -> 265-tiles track
episode 798, score -2.4848484848485306, frames 30, total_steps 27160, network actions 3350
Track generation: 1182..1489 -> 307-tiles track
episode 799, score -11.1601307189542

episode 849, score 1.7725490196077693, frames 32, total_steps 28971, network actions 3770
Track generation: 1051..1329 -> 278-tiles track
episode 850, score -3.4292418772563735, frames 29, total_steps 29000, network actions 3773
Track generation: 1163..1458 -> 295-tiles track
episode 851, score -11.093197278911536, frames 27, total_steps 29027, network actions 3779
Track generation: 1148..1439 -> 291-tiles track
episode 852, score -6.062068965517241, frames 34, total_steps 29061, network actions 3794
Track generation: 1180..1479 -> 299-tiles track
episode 853, score 42.836912751677886, frames 59, total_steps 29120, network actions 3813
Track generation: 1169..1472 -> 303-tiles track
episode 854, score 11.346357615893943, frames 39, total_steps 29159, network actions 3820
Track generation: 1172..1461 -> 289-tiles track
episode 855, score -9.066666666666627, frames 33, total_steps 29192, network actions 3829
Track generation: 1435..1797 -> 362-tiles track
episode 856, score 5.21108033240

episode 905, score 11.535658914728593, frames 37, total_steps 30964, network actions 4307
Track generation: 1207..1513 -> 306-tiles track
episode 906, score -5.749180327868858, frames 29, total_steps 30993, network actions 4320
Track generation: 1087..1363 -> 276-tiles track
episode 907, score 15.572727272727178, frames 39, total_steps 31032, network actions 4328
Track generation: 1110..1397 -> 287-tiles track
episode 908, score 14.35454545454536, frames 37, total_steps 31069, network actions 4336
Track generation: 1164..1459 -> 295-tiles track
episode 909, score 9.416326530612174, frames 38, total_steps 31107, network actions 4346
Track generation: 1197..1510 -> 313-tiles track
episode 910, score -6.864102564102549, frames 31, total_steps 31138, network actions 4352
Track generation: 1015..1273 -> 258-tiles track
episode 911, score 25.465758754863693, frames 43, total_steps 31181, network actions 4365
Track generation: 1044..1313 -> 269-tiles track
episode 912, score 72.27164179104527

episode 961, score 9.762499999999918, frames 31, total_steps 33068, network actions 4880
Track generation: 1155..1447 -> 292-tiles track
episode 962, score 10.137113402061765, frames 37, total_steps 33105, network actions 4891
Track generation: 1072..1344 -> 272-tiles track
episode 963, score 34.00073800737985, frames 66, total_steps 33171, network actions 4911
Track generation: 1149..1440 -> 291-tiles track
episode 964, score 8.02758620689638, frames 56, total_steps 33227, network actions 4929
Track generation: 1079..1353 -> 274-tiles track
episode 965, score -3.0589743589744174, frames 29, total_steps 33256, network actions 4933
Track generation: 1184..1494 -> 310-tiles track
episode 966, score -6.046278317152108, frames 29, total_steps 33285, network actions 4935
Track generation: 983..1233 -> 250-tiles track
episode 967, score 60.301606425703085, frames 67, total_steps 33352, network actions 4956
Track generation: 1060..1329 -> 269-tiles track
episode 968, score 19.338805970149153,

In [ ]:
from keras.models import load_model

agent.model.load_weights('model.h5')

In [ ]:
a = np.array([[1, 2], [3, 4]])
mask = np.zeros(a.shape, dtype=bool)
b = np.array([0,1])
# mask[b] = True
# np.ma.masked_array(a, b)


In [ ]:
for _ in range(20):
    env.render()
    obs, r, d, _ = env.step(env.action_space.sample())
    
plt.imshow(obs)

In [ ]:
obs = env.reset()

In [ ]:
env.close()

In [ ]:
plt.imshow(obs)

In [ ]:
ob2 = np.swapaxes(obs, 0, 2)

In [ ]:
ob2.shape

In [ ]:
obs.shape

In [ ]:
o = np.reshape(obs, (3,96,96))

In [ ]:
o == ob2

In [ ]:
from torchvision import transforms    

o = transforms.ToPILImage()(obs)

In [ ]:
o

In [ ]:
torch.device('cpu')

In [ ]:
from skimage import color

def process_image(img):
    return 2 * color.rgb2gray(img) - 1

In [ ]:
# agent.training_model.load_state_dict(torch.load('checkpoint.pth', map_location='cpu'))

for i in range(10):
#     states = deque(maxlen = 3)
    state = env.reset()
    for j in range(500):  
        state = process_image(state)
        action_idx = agent.get_action_for_state([state, state, state])
        print(action_idx)
        env.render()
        state, reward, done, _ = env.step(agent.action_map[action_idx])
        if done:
            break 
            
env.close()

In [ ]:
state = env.reset()
state = process_image(state)
for _ in range(1000):
    print('-------------------------------------')
    env.render()
    action_idx = get_random_action()
    action = all_actions[action_idx]
    print('Action -> ', action)
    next_state, reward, done, info = env.step(env.action_space.sample())
    print('Reward ->', reward)
    print('Done ->', done)
    next_state = process_image(next_state)
    print(next_state.shape)
    memory.add(state, action_idx, reward, next_state, done)
    state = next_state    
    print('-------------------------------------')


In [ ]:
4e-4

In [ ]:
env.close()

In [ ]:
a = [1,2,3,4,5,6]
a[-2:]

In [ ]:
a = np.ones(12)
a[1] = 9
a[2] = 9
a[3] = 9
b = np.ones(3, dtype='int32')
b[0] = 1
b[1] = 2
b[2] = 3

a[b]