In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

import gym
env = gym.make('CarRacing-v0')

import numpy as np
import itertools as it

from keras_agent import DQNAgent

# import torch
# import torch.nn.functional as F
# import torch.optim as optim

Using TensorFlow backend.


In [2]:
agent = DQNAgent(env)

---------- Initializing -----------
Action Map ->  [[-1.   1.   0.2]
 [-1.   1.   0. ]
 [-1.   0.   0.2]
 [-1.   0.   0. ]
 [ 0.   1.   0.2]
 [ 0.   1.   0. ]
 [ 0.   0.   0.2]
 [ 0.   0.   0. ]
 [ 1.   1.   0.2]
 [ 1.   1.   0. ]
 [ 1.   0.   0.2]
 [ 1.   0.   0. ]]


/Users/harsh/code/nn/project/f-dqn/keras_agent.py:97: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
  model.add(MaxPooling2D(pool_size = (2, 2), dim_ordering="th"))
/Users/harsh/code/nn/project/f-dqn/keras_agent.py:100: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
  model.add(MaxPooling2D(pool_size = (2, 2), dim_ordering="th"))


---------- Model ---------
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 8, 94, 94)         224       
_________________________________________________________________
batch_normalization_1 (Batch (None, 8, 94, 94)         376       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 47, 47)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 6, 45, 16)         6784      
_________________________________________________________________
batch_normalization_2 (Batch (None, 6, 45, 16)         64        
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 6, 22, 8)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1056)        

In [3]:
scores = []
frames_in_episodes = []
for i in range(1000):
    score, frames = agent.play_episode()
    scores.append(score)
    frames_in_episodes.append(frames)
    print(i, score, frames)
#     if i % 500 == 0:
#         torch.save(agent.training_model.state_dict(), 'checkpoint.pth')

Track generation: 1179..1478 -> 299-tiles track
0 0.3013422818791298 33
Track generation: 1035..1302 -> 267-tiles track
1 -8.403007518796965 24
Track generation: 1219..1538 -> 319-tiles track
2 -6.387421383647796 28
Track generation: 1101..1385 -> 284-tiles track
3 0.7021201413426787 37
Track generation: 1032..1299 -> 267-tiles track
4 53.72556390977468 55
Track generation: 1280..1604 -> 324-tiles track
5 -3.9321981424149115 29
Track generation: 1195..1498 -> 303-tiles track
6 21.28013245033101 39
Track generation: 1132..1419 -> 287-tiles track
7 7.961538461538382 35
Track generation: 957..1205 -> 248-tiles track
8 -0.05991902834014695 28
Track generation: 1224..1534 -> 310-tiles track
9 11.271197411003165 36
Track generation: 1108..1389 -> 281-tiles track
10 -9.642857142857114 25
Track generation: 1222..1537 -> 315-tiles track
11 18.955414012738757 40
Track generation: 1081..1355 -> 274-tiles track
12 27.208058608058515 38
Track generation: 1303..1633 -> 330-tiles track
13 19.67173252

KeyboardInterrupt: 

In [ ]:
from keras.models import load_model

agent.model.load_weights('model.h5')

In [ ]:
a = np.array([[1, 2], [3, 4]])
mask = np.zeros(a.shape, dtype=bool)
b = np.array([0,1])
# mask[b] = True
# np.ma.masked_array(a, b)


In [ ]:
for _ in range(20):
    env.render()
    obs, r, d, _ = env.step(env.action_space.sample())
    
plt.imshow(obs)

In [ ]:
obs = env.reset()

In [ ]:
env.close()

In [ ]:
plt.imshow(obs)

In [ ]:
ob2 = np.swapaxes(obs, 0, 2)

In [ ]:
ob2.shape

In [ ]:
obs.shape

In [ ]:
o = np.reshape(obs, (3,96,96))

In [ ]:
o == ob2

In [ ]:
from torchvision import transforms    

o = transforms.ToPILImage()(obs)

In [ ]:
o

In [ ]:
torch.device('cpu')

In [ ]:
from skimage import color

def process_image(img):
    return 2 * color.rgb2gray(img) - 1

In [ ]:
# agent.training_model.load_state_dict(torch.load('checkpoint.pth', map_location='cpu'))

for i in range(10):
#     states = deque(maxlen = 3)
    state = env.reset()
    for j in range(500):  
        state = process_image(state)
        action_idx = agent.get_action_for_state([state, state, state])
        print(action_idx)
        env.render()
        state, reward, done, _ = env.step(agent.action_map[action_idx])
        if done:
            break 
            
env.close()

In [ ]:
state = env.reset()
state = process_image(state)
for _ in range(1000):
    print('-------------------------------------')
    env.render()
    action_idx = get_random_action()
    action = all_actions[action_idx]
    print('Action -> ', action)
    next_state, reward, done, info = env.step(env.action_space.sample())
    print('Reward ->', reward)
    print('Done ->', done)
    next_state = process_image(next_state)
    print(next_state.shape)
    memory.add(state, action_idx, reward, next_state, done)
    state = next_state    
    print('-------------------------------------')


In [ ]:
4e-4

In [ ]:
env.close()

In [ ]:
a = [1,2,3,4,5,6]
a[-2:]

In [ ]:
a = np.ones(12)
a[1] = 9
a[2] = 9
a[3] = 9
b = np.ones(3, dtype='int32')
b[0] = 1
b[1] = 2
b[2] = 3

a[b]