In [2]:
!pip install gym
!pip install gym[Box2D]

    100% |████████████████████████████████| 450kB 8.2MB/s 


In [3]:
!apt-get install python-opengl -y

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-410
Use 'apt autoremove' to remove it.
Suggested packages:
  libgle3
The following NEW packages will be installed:
  python-opengl
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 496 kB of archives.
After this operation, 5,416 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python-opengl all 3.1.0+dfsg-1 [496 kB]
Fetched 496 kB in 2s (263 kB/s)
Selecting previously unselected package python-opengl.
(Reading database ... 131304 files and directories currently installed.)
Preparing to unpack .../python-opengl_3.1.0+dfsg-1_all.deb ...
Unpacking python-opengl (3.1.0+dfsg-1) ...
Setting up python-opengl (3.1.0+dfsg-1) ...


In [4]:
!apt install xvfb -y

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-410
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  xvfb
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 783 kB of archives.
After this operation, 2,266 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 xvfb amd64 2:1.19.6-1ubuntu4.2 [783 kB]
Fetched 783 kB in 2s (382 kB/s)
Selecting previously unselected package xvfb.
(Reading database ... 133659 files and directories currently installed.)
Preparing to unpack .../xvfb_2%3a1.19.6-1ubuntu4.2_amd64.deb ...
Unpacking xvfb (2:1.19.6-1ubuntu4.2) ...
Setting up xvfb (2:1.19.6-1ubuntu4.2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...


In [5]:
!pip install pyvirtualdisplay

  Stored in directory: /root/.cache/pip/wheels/d1/8c/16/1c64227974ae29c687e4cc30fd691d5c0fd40f54446dde99da
  Stored in directory: /root/.cache/pip/wheels/41/22/19/af15ef6264c58b625a82641ed7483ad05e258fbd8925505227
Successfully built pyvirtualdisplay EasyProcess


In [6]:
!pip install piglet

    100% |████████████████████████████████| 61kB 2.3MB/s 
    100% |████████████████████████████████| 92kB 6.4MB/s 
  Stored in directory: /root/.cache/pip/wheels/c7/59/a5/5bd1a35a4a4596714c4c7925a1751e7b1580b6ced363fd7969
Successfully built piglet


In [1]:
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

<Display cmd_param=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1009'] cmd=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1009'] oserror=None return_code=None stdout="None" stderr="None" timeout_happened=False>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# This code creates a virtual display to draw game images on. 
# If you are running locally, just ignore it
import os
if type(os.environ.get("DISPLAY")) is not str or len(os.environ.get("DISPLAY"))==0:
    !bash ../xvfb start
    %env DISPLAY=:1


**OpenAI Gym**

We're gonna spend several next weeks learning algorithms that solve decision processes. We are then in need of some interesting decision problems to test our algorithms.

That's where OpenAI gym comes into play. It's a python library that wraps many classical decision problems including robot control, videogames and board games.

So here's how it works:


In [3]:
import gym
env = gym.make("CarRacing-v0")

import itertools as it
from keras_agent import DQNAgent

Using TensorFlow backend.


In [0]:
import torch
import torch.nn.functional as F
import torch.optim as optim

reset() - reset environment to initial state, return first observation

render() - show current environment state (a more colorful version :) )

step(a) - commit action a and return (new observation, reward, is done, info)


In [5]:
agent = DQNAgent(env)
agent.render = False

---------- Initializing -----------
Action Map ->  [[-1.   1.   0.2]
 [-1.   1.   0. ]
 [-1.   0.   0.2]
 [-1.   0.   0. ]
 [ 0.   1.   0.2]
 [ 0.   1.   0. ]
 [ 0.   0.   0.2]
 [ 0.   0.   0. ]
 [ 1.   1.   0.2]
 [ 1.   1.   0. ]
 [ 1.   0.   0.2]
 [ 1.   0.   0. ]]
Instructions for updating:
Colocations handled automatically by placer.


/content/keras_agent.py:98: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
  model.add(MaxPooling2D(pool_size = (2, 2), dim_ordering="th"))
/content/keras_agent.py:101: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
  model.add(MaxPooling2D(pool_size = (2, 2), dim_ordering="th"))


---------- Model ---------
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 8, 94, 94)         224       
_________________________________________________________________
batch_normalization_1 (Batch (None, 8, 94, 94)         376       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 47, 47)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 6, 45, 16)         6784      
_________________________________________________________________
batch_normalization_2 (Batch (None, 6, 45, 16)         64        
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 6, 22, 8)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1056)        

In [0]:
scores = []
frames_in_episodes = []
for i in range(10100):
    score, frames = agent.play_episode()
    scores.append(score)
    frames_in_episodes.append(frames)
    print('Episode -> {} Reward -> {} Frames -> {} Playsteps -> {} Network Actions -> {}'.format(i, score, frames, agent.global_counter, agent.network_chosen_action))
    if i % 500 == 0:
#       torch.save(agent.training_model.state_dict(), 'checkpoint.pth')
        # serialize model to JSON
        model_json = agent.model.to_json()
        with open("model.json", "w") as json_file:
            json_file.write(model_json)
        # serialize weights to HDF5
        agent.model.save_weights("model.h5")
        print("Saved model to disk")
    if i % 100 == 0:
      print('---------------------------------------')
      print('Average Score for last 100 episodes -> ', sum(scores[-100:])/100)
      print('---------------------------------------')

Track generation: 1064..1334 -> 270-tiles track
Episode -> 0 Reward -> 17.227137546468306 Frames -> 37 Playsteps -> 37 Network Actions -> 0
Saved model to disk
---------------------------------------
Average Score for last 100 episodes ->  0.17227137546468307
---------------------------------------
Track generation: 1172..1469 -> 297-tiles track
Episode -> 1 Reward -> -8.429729729729695 Frames -> 29 Playsteps -> 66 Network Actions -> 0
Track generation: 1141..1438 -> 297-tiles track
Instructions for updating:
Use tf.cast instead.
Episode -> 2 Reward -> 14.697297297297204 Frames -> 42 Playsteps -> 108 Network Actions -> 0
Track generation: 1253..1570 -> 317-tiles track
Episode -> 3 Reward -> 1.1455696202530987 Frames -> 35 Playsteps -> 143 Network Actions -> 0
Track generation: 1214..1531 -> 317-tiles track
Episode -> 4 Reward -> 1.7455696202531001 Frames -> 33 Playsteps -> 176 Network Actions -> 0
Track generation: 1150..1442 -> 292-tiles track
Episode -> 5 Reward -> 20.446391752577227

In [0]:
sum(scores[-100:])/100

NameError: ignored